import type { Template } from '@/types/template';

export const TEMPLATES: Template[] = [
  {
    id: 'template1',
    name: '템플릿1',
    thumbnail: '/assets/templates/template1_thumb.png',
    background: '/assets/templates/template1.png',
    elements: [
      {
        id: 'text1',
        type: 'text',
        content: '방문한 식당에 대한 간단한 후기를 추가해주세요!',
        x: 314,
        y: 70,
        width: 330,
        height: 33,
        fontSize: 14,
        backgroundColor: '#ffffff',
        color: '#000000',
      },
      {
        id: 'tag1',
        type: 'tag',
        content: '@ 가게명',
        x: 435,
        y: 110,
        width: 84,
        height: 32,
        fontSize: 14,
        backgroundColor: '#FA4D09',
        color: '#ffffff',
      },
      {
        id: 'tag2',
        type: 'tag',
        content: '# 키워드',
        x: 439,
        y: 150,
        width: 80,
        height: 32,
        fontSize: 14,
        backgroundColor: '#ffffff',
        color: '#FA4D09',
      },
      {
        id: 'tag3',
        type: 'tag',
        content: '# 키워드',
        x: 439,
        y: 190,
        width: 80,
        height: 32,
        fontSize: 14,
        backgroundColor: '#ffffff',
        color: '#FA4D09',
      },
      {
        id: 'sticker1',
        type: 'sticker',
        src: '/assets/stickers/sticker3.svg',
        x: 390,
        y: 670,
        width: 160,
        height: 240,
        rotation: 0,
      },
    ],
  },
  {
    id: 'template2',
    name: '템플릿2',
    thumbnail: '/assets/templates/template2_thumb.png',
    background: '/assets/templates/template2.png',
    elements: [
      {
        id: 'text1',
        type: 'text',
        content: '방문한 식당에 대한 간단한 후기를 추가해주세요!',
        x: 256,
        y: 100,
        width: 290,
        height: 40,
        fontSize: 14,
        backgroundColor: '#ffffff',
        color: '#000000',
      },
      {
        id: 'tag1',
        type: 'tag',
        content: '@ 가게명',
        x: 155,
        y: 150,
        width: 84,
        height: 32,
        fontSize: 14,
        backgroundColor: '#FA4D09',
        color: '#ffffff',
      },
      {
        id: 'tag2',
        type: 'tag',
        content: '# 키워드',
        x: 245,
        y: 150,
        width: 80,
        height: 32,
        fontSize: 14,
        backgroundColor: '#ffffff',
        color: '#FA4D09',
      },
      {
        id: 'tag3',
        type: 'tag',
        content: '# 키워드',
        x: 333,
        y: 150,
        width: 80,
        height: 32,
        fontSize: 14,
        backgroundColor: '#ffffff',
        color: '#FA4D09',
      },
    ],
  },
  {
    id: 'template3',
    name: '템플릿3',
    thumbnail: '/assets/templates/template3_thumb.png',
    background: '/assets/templates/template3.png',
    elements: [
      {
        id: 'sticker1',
        type: 'sticker',
        src: '/assets/stickers/sticker6.svg',
        x: 380,
        y: 110,
        width: 140,
        height: 140,
        rotation: 0,
      },
      {
        id: 'text1',
        type: 'text',
        content: '방문한 식당에 대한 간단한 후기를 추가해주세요!',
        x: 250,
        y: 580,
        width: 290,
        height: 40,
        fontSize: 14,
        color: '#FFFFFF',
        backgroundColor: '#000000',
      },
    ],
  },
  {
    id: 'template4',
    name: '템플릿4',
    thumbnail: '/assets/templates/template4_thumb.png',
    background: '/assets/templates/template4.png',
    elements: [
      {
        id: 'sticker1',
        type: 'sticker',
        src: '/assets/stickers/sticker1.svg',
        x: 100,
        y: 250,
        width: 80,
        height: 80,
        rotation: 0,
      },
      {
        id: 'sticker2',
        type: 'sticker',
        src: '/assets/stickers/sticker2.svg',
        x: 385,
        y: 225,
        width: 100,
        height: 100,
        rotation: 0,
        flipX: true,
      },
      {
        id: 'text1',
        type: 'text',
        content: '방문한 식당에 대한 간단한 후기를 추가해주세요!',
        x: 250,
        y: 110,
        width: 290,
        height: 40,
        fontSize: 14,
        color: '#000000',
        backgroundColor: '#ffffff',
      },
      {
        id: 'tag1',
        type: 'tag',
        content: '@ 가게명',
        x: 160,
        y: 630,
        width: 84,
        height: 32,
        fontSize: 14,
        backgroundColor: '#FA4D09',
        color: '#ffffff',
      },
      {
        id: 'tag2',
        type: 'tag',
        content: '# 키워드',
        x: 255,
        y: 630,
        width: 80,
        height: 32,
        fontSize: 14,
        backgroundColor: '#ffffff',
        color: '#FA4D09',
      },
      {
        id: 'tag3',
        type: 'tag',
        content: '# 키워드2',
        x: 350,
        y: 630,
        width: 89,
        height: 32,
        fontSize: 14,
        backgroundColor: '#ffffff',
        color: '#FA4D09',
      },
    ],
  },
  {
    id: 'template5',
    name: '템플릿5',
    thumbnail: '/assets/templates/template5_thumb.png',
    background: '/assets/templates/template5.png',
    elements: [
      {
        id: 'text1',
        type: 'text',
        content: '방문한 식당에 대한 간단한 후기를 추가해주세요!',
        x: 270,
        y: 110,
        width: 290,
        height: 40,
        fontSize: 14,
        color: '#000000',
        backgroundColor: '#ffffff',
      },
      {
        id: 'sticker1',
        type: 'sticker',
        src: '/assets/stickers/sticker5.svg',
        x: 80,
        y: 510,
        width: 120,
        height: 120,
        rotation: 0,
      },
      {
        id: 'tag1',
        type: 'tag',
        content: '@ 가게명',
        x: 107,
        y: 589,
        width: 84,
        height: 32,
        fontSize: 14,
        backgroundColor: '#FA4D09',
        color: '#ffffff',
      },
      {
        id: 'tag2',
        type: 'tag',
        content: '# 키워드',
        x: 105,
        y: 626,
        width: 80,
        height: 32,
        fontSize: 14,
        backgroundColor: '#ffffff',
        color: '#FA4D09',
      },
      {
        id: 'tag3',
        type: 'tag',
        content: '# 키워드',
        x: 190,
        y: 626,
        width: 80,
        height: 32,
        fontSize: 14,
        backgroundColor: '#ffffff',
        color: '#FA4D09',
      },
    ],
  },
  {
    id: 'template6',
    name: '템플릿6',
    thumbnail: '/assets/templates/template6_thumb.png',
    background: '/assets/templates/template6.png',
    elements: [
      {
        id: 'tag1',
        type: 'tag',
        content: '@ 가게명',
        x: 360,
        y: 310,
        width: 84,
        height: 32,
        fontSize: 14,
        backgroundColor: '#FA4D09',
        color: '#ffffff',
      },
      {
        id: 'sticker1',
        type: 'sticker',
        src: '/assets/stickers/sticker10.svg',
        x: 270,
        y: 490,
        width: 170,
        height: 170,
        rotation: 12.823,
      },
    ],
  },
];
