import Header from '@/components/layout/Header';
import Providers from '@/providers/RQProvider';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import './globals.css';


export const metadata: Metadata = {
  title: 'Local Eat',
  description: 'Generated by create next app',
  icons: {
    icon: '/assets/icons/profile1.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col antialiased`}>
        <Header />
        <Providers>{children}</Providers>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
